# PANDAS

In [2]:
import pandas as pd

## Create a dataFrame (table)

In [5]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [6]:
df = pd.DataFrame(data, columns=columns)

In [10]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

## Access Data

In [12]:
df.head(1)

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000

In [16]:
df.Make

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: str

In [17]:
df["Model"]

0      Stanza
1      Sonata
2       Elise
3      Acadia
4    Frontier
Name: Model, dtype: str

In [18]:
df[["Make", "Model"]]

      Make     Model
0   Nissan    Stanza
1  Hyundai    Sonata
2    Lotus     Elise
3      GMC    Acadia
4   Nissan  Frontier

## Set and Delete Columns

In [23]:
df["id"] = [1,2,3,4,5]

In [21]:
del df["id"]

In [24]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,3
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,4
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,5

## Index

In [26]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [29]:
df.index = ['a', 'b', 'c', 'd', 'e'] # change index values

In [36]:
df.loc['b'] # loc -> location

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2
a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1

In [37]:
df.loc[['b', 'a']] # loc -> location multiple

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2
a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1

In [39]:
df.iloc[1] # positional index

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
id                           2
Name: b, dtype: object

In [44]:
df.reset_index(drop=True) # drop -> whether drop the old index or if false add this as new col index

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,3
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,4
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,5

In [41]:
df # old one as reset create new one

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP,id
a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000,1
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150,2
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990,3
d,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450,4
e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340,5